beamer: agent: use the RPC gas strategy
This avoids the following error when running the agent in a Boba -> Metis scenario:

    ValueError: {'code': -32601, 'message': 'the method eth_maxPriorityFeePerGas does not exist/is not available'}